### ISSUE TITLE
Join the PF2e-Foundry discord server?

### ISSUE THREAD

**Issue by SpinazFou** [reyzor1991/foundry-vtt-pf2e-reaction#10]
https://discord.gg/HESxH9GV
You can post your updates here (Module-Releases channel) for this useful module, so most people can see.
This is an excellent module idea. Well played.

P.s. if you want an idea for another module that still doesnt exist (critical in my opinion) is the Automatic Detection. Fighting multiple opponents and not having to roll flat checks and whatnot would help a lot. This would bring a lot of timesaving to the GMs. https://www.youtube.com/watch?v=9qOleg3NZjA&ab_channel=KingOogaTonTon

**Comment by reyzor1991** [comment]
Now I member of PF2e-Foundry discord server
I will think about Automatic Detection module
PF2e Flat Check cover of some slat checks
