### ISSUE TITLE
If the last message in game.messages already is an attack of opportunity message, avoid making another one.

### ISSUE THREAD

**Issue by xdy** [reyzor1991/foundry-vtt-pf2e-reaction#12]
As in, don't repeat the question to use reaction for every part of a creature's move (Might be a good idea to update the last message with something like '(happened 4 times)'
This is to avoid situations like the following, which quickly filled the chat window:
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/246024/52b63413-34eb-4ab0-aad6-9d2dd2e5aaca)
Yes, I probably should drag to move to the final location, but, mistakes happen. :)

**Comment by reyzor1991** [comment]
I will think about how to group messages correctly  with attack of opportunity, but need also think about situation when player has more than 1 reaction

**Comment by xdy** [comment]
Maybe something like:
```
If any reactions are left
  If last message isn't already an unhandled reminder
    Output message
       On yes, remove one reaction and consider it handled
       On no,  consider it handled
```
Handled might be setting a flag, or, perhaps better, simply removing the message.

**Comment by reyzor1991** [comment]
Grouping messages was added in last version
