### ISSUE TITLE
Bug : Player doesn't get the chat message

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/foundry-vtt-pf2e-reaction#14]
**Describe the bug**
When the GM see the chat message for a possible reaction, the player who owned the token doesn't see it too, even with the option to send player notification enabled.

**To Reproduce**
Foundry v10 last stable
System last version
Module last version

**Expected behavior**
Player should see the message with the question to use his reaction or not.

**Comment by reyzor1991** [comment]
fixed 0.1.39
