### ISSUE TITLE
Homebrew Addons/system to add our on reactions

### ISSUE THREAD

**Issue by cadowtin** [reyzor1991/foundry-vtt-pf2e-reaction#15]
Specifically looking at for my case the reactions added by **everything shields**, don't believe they should be part of the main module (because homebrew), but if there was some way for me to either create a companion module that extends off this (maybe a homebrew repo for people to add reactions?) Or something of that nature that'd be cool I guess.

**Comment by reyzor1991** [comment]
I think it's possible to add mechanism for manual adding homebrew reactions and handle them.

Is it possible to add few reaction descriptions from "everything shields"? I need few examples for it.

**Comment by reyzor1991** [comment]
@cadowtin Added in 0.2.0

**Comment by cadowtin** [comment]
Some example ones:
Pre req for most reactions - A shield with x trait is raised
- An adjacent enemy uses an action with the concentrate trait.
- An ally within 15 feet is hit by a ranged weapon attack, and a
 +2 circumstance bonus to AC would turn the critical hit into a hit or
 the hit into a miss.
-  A foe critically fails a melee attack against you.
- An ally attempts a skill check against an enemy that you are
 adjacent to.
- You and at least one other ally are in an area of effect that
 deals damage or has the visual trait.
-  An adjacent enemy critically fails an attack against you or an
 ally.

Those are the reactions, don't stress about it, if it's not feasible or would take too long feel free to ignore, sorry for late response

**Comment by reyzor1991** [comment]
@cadowtin not a problem, I will implement it 
some features already exist:

-   FailSavingThrow,
-   CriticallyHitCreature,
-   EnemyUseManipulateAction,
-   EnemyUseMoveAction,
-   EnemyUseRangedAttack,
-   AllyTakeDamage,
-   ActorTakeDamage,
-   CreatureAttacksAlly,
-   YouHPZero,
-   AllyHPZero,
-   EnemyUsesTrait,
-   EnemyCastSpell,
-   EnemyHitsActor,
-   EnemyCriticallyFailHitsActor,
-   EnemyFailHitsActor,
-   ActorFailsHit,
-   ActorFailsSkillCheck

Now without checking requirement trigger, but it's next step
