### ISSUE TITLE
Reaction reminder pops up when the actor is unconscious/dead

### ISSUE THREAD

**Issue by elemorelli** [reyzor1991/foundry-vtt-pf2e-reaction#16]
**Describe the bug**
When unconscious/dead, reminders still appears on chat but unconscious characters are unable to act. It happens on NPCs and PCs.

**To Reproduce**

1. Give the Attack of Opportunity feature to a character.
2. Create an encounter with an enemy next to the other.
3. Give 0 HP and/or the unconscious/dead condition to one of them.
4. Start the encounter and move one of these out of the 5 ft reach.
5. An Attack of Opportunity reminder appears on chat.

**Expected behavior**
The Attack of Opportunity reminder shouldn't appear, as one of the actors can't act

**Screenshots**

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/1661552/212b459f-34cd-4c50-bc09-b291326eefa8)
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/1661552/d0e38457-cb6b-4eff-87cf-6ff53bd4095b)

**Comment by reyzor1991** [comment]
Fixed 0.2.3
