### ISSUE TITLE
Add trigger "Critically Fail a Saving Throw"

### ISSUE THREAD

**Issue by maplealmond** [reyzor1991/foundry-vtt-pf2e-reaction#18]
The spell Schadenfreude requires a *critical* failure of a saving throw as a trigger.  Currently only a failed saving throw of any type can be used.

See: https://2e.aonprd.com/Spells.aspx?ID=991

Note that this is not the only feature or spell which depends on a critical failure saving throw.  e.g.  https://2e.aonprd.com/Feats.aspx?ID=3031 or https://2e.aonprd.com/Feats.aspx?ID=2246

**Comment by reyzor1991** [comment]
0.2.7

- EnemyCriticalHitsActor,CriticalFailSavingThrow were added as trigger
-   Add Schadenfreude reaction check
