### ISSUE TITLE
Improve looks of Recall Knowledge buttons or make labels clickable instead. 

### ISSUE THREAD

**Issue by apoapostolov** [reyzor1991/foundry-vtt-pf2e-reaction#20]
Recall Knowledge buttons have a very crude CSS that causes significant vertical bloat that pushes attacks and abilities very low and out of screen (for smaller screens). It would be much better if the buttons were much smaller, or instead of buttons of so many Lores that may never exist in the game at all, the labels in the box (much smaller and default sized) were clickable to trigger the behavior. 

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/4083812/21651fd3-7110-4257-aaa0-fefb06988ef2)

**Comment by reyzor1991** [comment]
@apoapostolov 
New view of Recall Knowledge
<img width="708" alt="Screenshot 2023-07-17 at 13 24 15" src="https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/0bbbdc2d-12b9-4234-b6c9-ca46f2b2a95e">


Also new setting to add specific lore

<img width="543" alt="Screenshot 2023-07-17 at 13 26 37" src="https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/d77388d0-89b2-4fe8-b5b9-35351e048712">

**Comment by reyzor1991** [comment]
@apoapostolov If you have specific lore which you use as easy DC or very easy DC I would like to add it to module

**Comment by apoapostolov** [comment]
This looks amazing. One question - if the existing labels and the new button labels have the same CSS, can you hide the existing labels that are not clickable and leave the new label-buttons that are clickable? Also, the hyperspecicic lore that is exactly the name of the creature is not something PF2 even suggests, as the most specific suggested types of Lore are based on creature traits and creature families.

**Comment by reyzor1991** [comment]
Hide not clickable label – not a problem.

Now lore easy DC – based on creature traits,
But can't find any other infos instead of name to create label with very easy DC

**Comment by apoapostolov** [comment]
That design space is defined but hasn't been developed in the game. You can let it as is, but very easy DC would make sense to be off by default.

**Comment by apoapostolov** [comment]
Looks and works great now, thanks!!

**Comment by reyzor1991** [comment]
Added in new release - 0.2.19

New settings
<img width="543" alt="recallSettings" src="https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/fadd1505-957e-414e-af5d-c8e5a78fedb2">

New view
<img width="710" alt="exampleKnowledge" src="https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/0a04595e-9567-46a7-b2ba-ece355f2c38d">
