### ISSUE TITLE
String when requesting knowledge may reveal creature name

### ISSUE THREAD

**Issue by apoapostolov** [reyzor1991/foundry-vtt-pf2e-reaction#21]
I suggest removing the creature's name because it may inadvertently reveal a name of a mysteriously described creature to the players. Just use "To Recall Knowledge, roll [clickable label]"

![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/4083812/aaaad49a-ef22-4e58-b740-09018da3441d)

**Comment by reyzor1991** [comment]
PC View
<img width="296" alt="Screenshot 2023-07-17 at 17 07 19" src="https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/ed6e2d66-04b3-4512-825d-64614e4810d9">

Gm View
<img width="289" alt="Screenshot 2023-07-17 at 17 08 27" src="https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/7df843e8-6a51-44ae-a744-97fc7571295c">

**Comment by reyzor1991** [comment]
Was changed in 0.2.20
