### ISSUE TITLE
Option to mark as friendly?

### ISSUE THREAD

**Issue by BuyMyMojo** [reyzor1991/foundry-vtt-pf2e-reaction#23]
I have an NPC marked as friendly towards the party (Under configure NPC alliance is set to Party) but whenever the players move in combat it tells me he can do an attach of oppertunity which gets really annoying every combat

**Comment by reyzor1991** [comment]
Was added in 0.2.23

**Comment by BuyMyMojo** [comment]
perfect! Will get back to you if I find any issues with it during my session this weekend

**Comment by reyzor1991** [comment]
Great, thank you for your help
