### ISSUE TITLE
Use the action when clicking "Yes"

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/foundry-vtt-pf2e-reaction#24]
Hi, would that be possible to actually use the action (send the reaction card in the chat) when clicking on the "Yes" when asked if the reaction was used ? There is already a button of the reaction coming with the question, but unless I'm missing something we can't interact with it to actually use the reaction and send the chat card. If that could be done by clicking Yes" it would spare the time to search the reaction in the sheet to send the chat card, and let the player target before clicking "Yes" to automate the effect of the reaction if there are any.

**Comment by reyzor1991** [comment]
I think I will try to automate this process, but with targeting it be more hardly
Maybe for start it would be "Yes (Choose target)", if need to target or  "Yes" not

**Comment by uniwars** [comment]
Idk how it works behind the scene, but for example with Action support, if I target my ally when he triggers a reactive strike and then click "Yes", if clicking Yes only send the reaction chat card, wouldn't that count as if I clicked on it in my sheet and do the Action support automation as well, using the token I already targeted before clicking Yes as the target ?

**Comment by reyzor1991** [comment]
Example

https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/d61c712b-c76e-437e-bd61-5e4c64603b82

**Comment by reyzor1991** [comment]
In this case, need to update actions, and Button "Yes (Choose target)" it's only visual I can't target ally or smth else

**Comment by uniwars** [comment]
so if I understand it right :
the (choose target) part on the button does nothing, it's just a reminder for the user to choose a target before clicking on it ?

and even if the user already has a target he needs to refresh it before clicking ?

either way it's already awesome

**Comment by reyzor1991** [comment]
Yes, it's just a reminder

Not need to refresh, but need to target at correct actor because effect would be applied to target

**Comment by reyzor1991** [comment]
Fix issue

Could you create video for 2 issue?

https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/6688366/74af71ba-71c8-4da4-b06d-e89093e3a197

**Comment by uniwars** [comment]
all works fine, thank for your hard work
