### ISSUE TITLE
polyglot conflict

### ISSUE THREAD

**Issue by dharkus5000** [reyzor1991/foundry-vtt-pf2e-reaction#26]
when the language you're "speaking" in isn't common (via the polyglot module), the RK buttons don't parse correctly into a button, but output the code for what makes up a button, which, along with not working as a button, tells the players the DC.
it's possible that if you're speaking in the default language and the players have the same one set it might work, but it's worked for only some players and not others
it's possible this is a problem with polyglot and not this module?

**Comment by reyzor1991** [comment]
Maybe polyglot module, but I need to check it, Is it possible to provide some screenshots or video?

**Comment by dharkus5000** [comment]
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/88220878/8c43e7e3-8f72-4b3f-b75f-8104a98d22ed)
here's an example with a random language that's not the default, then the default, common

**Comment by reyzor1991** [comment]
Look like issue in polyglot module. If I post @Check[type:stealth|dc:27] All is ok
But if add text → please do it @Check[type:stealth|dc:27], Get similar to your screenshot
