### ISSUE TITLE
Add Reaction Requirement in Homebrew Functions cant work

### ISSUE THREAD

**Issue by LiyuNodream** [reyzor1991/foundry-vtt-pf2e-reaction#29]
When making homebrew reaction, the Reaction Requirement cant work. I have already tried to write the clear UUID like 'Item.Id40YWaNIeG55CF7' in the blank, write full UUID like '@UUID[...]{...}' in it, even the simple name of the requirement thing. But it still dont work.

Is there fault in my steps? or it just have bugs? 

(the Trigger function can work)

I use v11 307 fvtt, the latest pf2e systems and the latest module version.

There's no F12 error.

**Comment by reyzor1991** [comment]
Could you create a screenshot of homebrew?

**Comment by reyzor1991** [comment]
For Requirement need to use slug. I updated UI in last version

**Comment by LiyuNodream** [comment]
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/110900345/20d53689-75da-4235-812d-9fef43b37a4f)
![image](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/110900345/74a7a2e4-e5c4-4e43-a363-379067e23d3d)
Emmm... I was using the 2.4.0 version I will now update the mod. Thanks!
