### ISSUE TITLE
Localization update

### ISSUE THREAD

**Issue by DoctorDankovsky** [reyzor1991/foundry-vtt-pf2e-reaction#30]
Updated the script and localization file. Files are attached. Not a programmer, so couldn't minify the script again.

[pf2e-reaction.zip](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/files/12678162/pf2e-reaction.zip)
[en.zip](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/files/12678164/en.zip)

**Comment by reyzor1991** [comment]
Done
