### ISSUE TITLE
Adding Counter to "Reaction was used" effect if an actor has more than one reaction

### ISSUE THREAD

**Issue by popydo** [reyzor1991/foundry-vtt-pf2e-reaction#32]
Hey, I was wondering if you could add a counter to the "Reaction was used" effect, when the actor has an additional reaction, e.g. from the Quick Shield Block feat. This would make tracking double reactions much easier <3 

https://2e.aonprd.com/Feats.aspx?ID=394

**Comment by reyzor1991** [comment]
Next release
