### ISSUE TITLE
Disarming Block

### ISSUE THREAD

**Issue by popydo** [reyzor1991/foundry-vtt-pf2e-reaction#34]
Disarming Block is something I always forget about, especially since not every enemy carries a weapon. Triggering when I block damage with a shield would be perfect (and adding to this the condition that the opponent attacks with a weapon would be perfectly perfect, but I don't think that's possibie?), but even triggering when taking damage would help much.

_Trigger You [Shield Block](https://2e.aonprd.com/Feats.aspx?ID=839) a melee Strike made with a held weapon.
You attempt to [Disarm](https://2e.aonprd.com/Actions.aspx?ID=41) the creature whose attack you blocked of the weapon they attacked you with. You can do so even if you don't have a hand free._

**Comment by reyzor1991** [comment]
Added next release, not sure that cover all cases
