### ISSUE TITLE
Having issues with:  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'OOC')

### ISSUE THREAD

**Issue by dannyice96** [reyzor1991/foundry-vtt-pf2e-reaction#40]
**Describe the bug**
I'm bad with codes things so not too sure if can describe it better than getting the error whenever trying to trigger Reactive Strike

**To Reproduce**
Moving an opposing token away from a token with Reactive Strike/AOO

**Expected behavior**
Chat message reminder about reactions and other stuff related to module.

**Screenshots**
![Screenshot 2024-07-10 000040](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/175139781/35462196-ff77-49b3-964f-7c3751f1a692)
![Screenshot 2024-07-10 000202](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/assets/175139781/8433a168-d764-4c27-8c91-ee9c478aa98a)

**Comment by reyzor1991** [comment]
Issue with compatibility v11 - fix ASAP

**Comment by dannyice96** [comment]
Works now! Thanks <3!
