### ISSUE TITLE
BUG: Schadenfreude reaction is triggered when the spell is not prepared

### ISSUE THREAD

**Issue by poindexter1985** [reyzor1991/foundry-vtt-pf2e-reaction#44]
**Describe the bug**
Reaction Checker always generates a message that Schadenfreude can be used as a reaction to a critically failed save, even if the spell is known but not prepared.

**To Reproduce**
- Create a wizard PC with a prepared spellcasting entry.
- Add Schadenfreude to the list of known spells known, but do not prepare it in any slots.
- Start a combat encounter with the wizard and any enemy with a saving throw effect (Giant Spider will do)
- Have the enemy send their saving throw ability into chat
- With the wizard selected, force a critical failure on the saving throw

**Expected behavior**
No reactions should be prompted for this character (unless other abilities have been added to grant other reactions)

**Screenshots**
![image](https://github.com/user-attachments/assets/5758f2cd-3b1d-4f4a-81ea-03fcc78dbe25)

**Comment by reyzor1991** [comment]
Fix in next release
