### ISSUE TITLE
Error opening Configure Settings

### ISSUE THREAD

**Issue by bsleys** [reyzor1991/foundry-vtt-pf2e-reaction#5]
I receive the below error when trying to open the Configure settings page with only this module loaded. The window does not open due to this error.

`Error: An error occurred while rendering SettingsConfig 109. Setting Model Validation Errors
[Setting.value]: may not be undefined
    ModelValidationError https://bobpf2.pve.ourea.solutions/scripts/commons.js:5116
    _validateType https://bobpf2.pve.ourea.solutions/scripts/commons.js:4098
    validate https://bobpf2.pve.ourea.solutions/scripts/commons.js:3824
    validate https://bobpf2.pve.ourea.solutions/scripts/commons.js:5492
    DataModel https://bobpf2.pve.ourea.solutions/scripts/commons.js:5269
    Document https://bobpf2.pve.ourea.solutions/scripts/commons.js:5811
    BaseSetting https://bobpf2.pve.ourea.solutions/scripts/commons.js:9832
    <anonymous> https://bobpf2.pve.ourea.solutions/scripts/foundry.js:13053
    Setting https://bobpf2.pve.ourea.solutions/scripts/foundry.js:21323
    get https://bobpf2.pve.ourea.solutions/scripts/foundry.js:2815
    _prepareCategoryData https://bobpf2.pve.ourea.solutions/scripts/foundry.js:71900
    getData https://bobpf2.pve.ourea.solutions/scripts/foundry.js:59851
    _render https://bobpf2.pve.ourea.solutions/scripts/foundry.js:5108
    _render https://bobpf2.pve.ourea.solutions/scripts/foundry.js:5822
    _render https://bobpf2.pve.ourea.solutions/scripts/foundry.js:59920
[foundry.js:747:30](https://bobpf2.pve.ourea.solutions/scripts/foundry.js)`

**Comment by reyzor1991** [comment]
@bsleys Could you please provide settings file Data/worlds/{world-name}/data/settings.db

**Comment by bsleys** [comment]
[settings.zip](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/files/11538180/settings.zip)

There you go.  Note this is happening in at least 2 worlds I tried this mod with today.

**Comment by reyzor1991** [comment]
Fixed 0.1.23
